version: '3.8'
services:

  auth_mysql:
    image: mysql
    container_name: auth_mysql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --default-authentication-plugin=mysql_native_password]
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/custom:/etc/mysql/conf.d
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${AA_DB_ROOT_PASSWORD}
    networks:
      - aa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-proot", "-h", "localhost", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  nginx:
    image: nginx:1.15.5
    container_name: aa-nginx
    labels:
      - "traefik.enable=true"
      - 'traefik.docker.network=traefik_proxy'
      - "traefik.http.routers.aaauth-app.entrypoints=websecure"
      - "traefik.http.routers.aaauth-app.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.aaauth-app.tls.certresolver=lets-encrypt"
      - "traefik.http.services.aaauth-app.loadbalancer.server.port=8080"
      - "traefik.http.routers.aaauth-app.service=aaauth-app"
      - 'traefik.http.services.aaauth-app.loadbalancer.server.port=80'
    volumes:
      - ./conf/local.conf:/etc/nginx/conf.d/default.conf
      - static-volume:/var/www/myauth/static
    depends_on:
      - allianceauth
    networks:
      - aa-network
      - traefik_proxy

  redis:
    image: redis:3
    container_name: aa-redis
    command: redis-server
    restart: always
    volumes:
      - "redis-data:/data"
    networks:
      - aa-network
    expose:
      - "6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  allianceauth:
    image: milleruk/allianceauth
    container_name: aa-auth
    restart: always
    #command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && /usr/bin/supervisord"
    ports:
      - 5555:5555
    environment:
      DB_HOST: "${AA_DB_HOST}"
      DB_NAME: "${AA_DB_NAME}"
      DB_USER: "${AA_DB_USER}"
      DB_PASSWORD: "${AA_DB_PASSWORD}"
    volumes:
      - ./conf/local.py:/home/allianceserver/myauth/myauth/settings/local.py
      - ./templates:/home/allianceserver//myauth/myauth/templates/
      - static-volume:/var/www/myauth/static
    depends_on:
     - redis
    networks:
      - aa-network
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
  aa-network:

volumes:
    redis-data:
    static-volume:
